import { afterEach, describe, expect, test } from 'bun:test';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  collectRepositoryViolations,
  extractAddedLines,
  hasAuthorshipMarker,
  hasDashPunctuation,
  isCopyPath,
  scanCommitMetadata,
} from '../../packaging/check-copy-hygiene.ts';

const DASH = String.fromCodePoint(0x2014);
const OPEN_AI = ['Open', 'AI'].join('');
const CODEX = ['Co', 'dex'].join('');
const CHAT_GPT = ['Chat', 'GPT'].join('');
const CLAUDE = ['Clau', 'de'].join('');
const AI_ASSISTANT = ['AI', 'assistant'].join(' ');
const phrase = (verb: string, connector: string, name: string): string =>
  `${verb} ${connector} ${name}`;
const trailer = (name: string): string =>
  `${['Co', 'authored'].join('-')}-by: ${name} <tool@example.test>`;

const temporaryRoots: string[] = [];
afterEach(() => {
  while (temporaryRoots.length > 0) rmSync(temporaryRoots.pop()!, { recursive: true, force: true });
});

const makeRepository = (): string => {
  const root = mkdtempSync(join(tmpdir(), 'peerd-copy-hygiene-'));
  temporaryRoots.push(root);
  const git = (...args: string[]) => execFileSync('git', args, { cwd: root, stdio: 'ignore' });
  git('init');
  git('checkout', '-b', 'main');
  git('config', 'user.name', 'Human Maintainer');
  git('config', 'user.email', 'human@example.test');
  writeFileSync(join(root, 'tracked.md'), `legacy ${DASH} allowed\n`);
  git('add', 'tracked.md');
  git('commit', '-m', 'initial');
  git('checkout', '-b', 'feature');
  return root;
};

describe('copy path scope', () => {
  test('includes authored source and excludes generated or vendored text', () => {
    expect(isCopyPath('README.md')).toBe(true);
    expect(isCopyPath('extension/sidepanel/app.js')).toBe(true);
    expect(isCopyPath('tests/example.test.ts')).toBe(true);
    expect(isCopyPath('extension/vendor/library.js')).toBe(false);
    expect(isCopyPath('vendor/library.js')).toBe(false);
    expect(isCopyPath('extension/manifest.json')).toBe(false);
    expect(isCopyPath('AGENTS.md')).toBe(false);
    expect(isCopyPath('CLAUDE.md')).toBe(false);
    expect(isCopyPath('nested/CODEX.md')).toBe(false);
    expect(isCopyPath('.agents/review.md')).toBe(false);
    expect(isCopyPath('.codex/instructions.md')).toBe(false);
    expect(isCopyPath('docs/security/RED-TEAM-RESULTS.md')).toBe(false);
    expect(isCopyPath('packaging/security-baseline.json')).toBe(false);
  });
});

describe('copy classifiers', () => {
  test('recognizes raw, HTML, JavaScript, and CSS dash forms', () => {
    const encodings = [
      DASH,
      '&' + 'mdash;',
      '&' + 'mdash ',
      '&#' + '8212;',
      '&#' + '8212 ',
      '&#0' + '8212;',
      '&#x' + '2014;',
      '&#x' + '2014 ',
      '\\' + 'u' + '2014',
      '\\' + 'u{' + '2014}',
      '\\' + 'u{' + '02014}',
      '\\' + '2014',
      '\\' + '02014',
      '\\' + '002014',
    ];
    for (const encoding of encodings) expect(hasDashPunctuation(`left${encoding}right`)).toBe(true);
    expect(hasDashPunctuation('left - right')).toBe(false);
    expect(hasDashPunctuation('left -- right')).toBe(false);
  });

  test('blocks assistant authorship while allowing provider and compatibility references', () => {
    for (const value of [
      phrase('Generated', 'with', CODEX),
      phrase('Written', 'by', OPEN_AI),
      phrase('Drafted', 'with', CHAT_GPT),
      phrase('Written', 'using', CODEX),
      phrase('Created', 'with', CLAUDE),
      phrase('Generated', 'by', `an ${AI_ASSISTANT}`),
      `${['AI', 'generated'].join('-')} change`,
      `${OPEN_AI}-generated documentation`,
      `Documentation generated with ${OPEN_AI}`,
      `Documentation output generated with ${OPEN_AI}`,
      `Change generated with ${OPEN_AI} API`,
      trailer(CODEX),
      trailer(CLAUDE),
    ]) expect(hasAuthorshipMarker(value)).toBe(true);

    for (const value of [
      `${OPEN_AI} provider`,
      `${OPEN_AI} API`,
      `${OPEN_AI}-compatible API`,
      `${CODEX} compatibility`,
      `${CODEX}-style metadata`,
      `generated an ${OPEN_AI} request`,
      `Response generated by ${OPEN_AI} API`,
      `Adapter output generated with ${OPEN_AI}`,
      `The model response was generated by ${OPEN_AI} provider`,
      `${OPEN_AI}-generated response`,
    ]) expect(hasAuthorshipMarker(value)).toBe(false);
  });
});

describe('added-line extraction', () => {
  test('keeps new-file line numbers and ignores deletion and context lines', () => {
    const patch = [
      'diff --git a/file.md b/file.md',
      '@@ -2,2 +2,3 @@',
      ' context',
      '-old',
      '+new one',
      '+new two',
      '@@ -9,0 +11,1 @@',
      '+last',
    ].join('\n');
    expect(extractAddedLines(patch)).toEqual([
      { line: 3, text: 'new one' },
      { line: 4, text: 'new two' },
      { line: 11, text: 'last' },
    ]);
  });
});

describe('commit metadata', () => {
  const base = {
    sha: '1234567890abcdef',
    authorName: 'Human Maintainer',
    authorEmail: 'human@example.test',
    committerName: 'Human Maintainer',
    committerEmail: 'human@example.test',
  };

  test('blocks assistant identities and marker prose', () => {
    expect(scanCommitMetadata({ ...base, authorName: CODEX, body: 'normal change' }))
      .toContainEqual(expect.objectContaining({ kind: 'authorship-marker' }));
    expect(scanCommitMetadata({ ...base, authorName: CLAUDE, body: 'normal change' }))
      .toContainEqual(expect.objectContaining({ kind: 'authorship-marker' }));
    expect(scanCommitMetadata({ ...base, authorName: 'AI', body: 'normal change' }))
      .toContainEqual(expect.objectContaining({ kind: 'authorship-marker' }));
    expect(scanCommitMetadata({ ...base, body: phrase('Generated', 'with', CODEX) }))
      .toContainEqual(expect.objectContaining({ kind: 'authorship-marker' }));
    expect(scanCommitMetadata({ ...base, body: `plain ${DASH} prose` }))
      .toContainEqual(expect.objectContaining({ kind: 'dash-punctuation' }));
  });

  test('allows ordinary provider work', () => {
    expect(scanCommitMetadata({ ...base, body: `feat: add ${OPEN_AI} provider` })).toEqual([]);
  });
});

describe('repository collection', () => {
  test('covers committed, staged, unstaged, untracked, and commit metadata additions', () => {
    const root = makeRepository();
    const git = (...args: string[]) => execFileSync('git', args, { cwd: root, stdio: 'ignore' });

    writeFileSync(join(root, 'committed.md'), `committed ${DASH} copy\n`);
    git('add', 'committed.md');
    git('commit', '-m', phrase('Generated', 'with', CODEX));

    writeFileSync(join(root, 'staged.md'), `staged ${DASH} copy\n`);
    git('add', 'staged.md');
    writeFileSync(join(root, 'tracked.md'), `legacy ${DASH} allowed\nunstaged ${DASH} copy\n`);
    writeFileSync(join(root, 'untracked.md'), `untracked ${DASH} copy\n`);

    const violations = collectRepositoryViolations(root);
    const dashPaths = violations
      .filter((violation) => violation.kind === 'dash-punctuation')
      .map((violation) => violation.path);
    expect(dashPaths).toEqual([
      'committed.md',
      'staged.md',
      'tracked.md',
      'untracked.md',
    ]);
    expect(violations.some((violation) =>
      violation.kind === 'authorship-marker' && violation.path.startsWith('commit:'))).toBe(true);
    expect(violations.some((violation) =>
      violation.kind === 'dash-punctuation'
      && violation.path === 'tracked.md'
      && violation.line === 1)).toBe(false);
  }, 15_000);
});
