// Vendor integrity gate. extension/vendor/ is third-party executable code
// that ships verbatim in every artifact, yet it is deliberately EXEMPT from
// the other source gates (hygiene, web-boundary, tscheck — "reviewed at
// vendoring time, not here"). That review happens once, at vendoring; this
// gate makes its outcome durable: every vendored byte is pinned in a
// machine-readable lock (extension/vendor/vendor.lock.json — per-file
// SHA-256, sorted paths, no timestamps), and CI + preflight fail on ANY
// divergence — a tampered file, an added file, a deleted file.
//
//   bun run check:vendor              verify vendor/ against the lock
//   bun packaging/check-vendor.ts --write   regenerate the lock (re-vendoring)
//
// why a lock and not the SOURCE.txt hashes: the per-dir SOURCE.txt files
// record upstream provenance in free-form prose (four different hash formats,
// some files unhashed) and nothing ever read them back. They remain the
// human-facing provenance record; this lock is the enforced one. A --write
// belongs in the SAME commit as the vendored change it blesses, where a
// reviewer sees both.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { EXTENSION_DIR } from './lib.ts';

const VENDOR_DIR = join(EXTENSION_DIR, 'vendor');
export const VENDOR_LOCK_PATH = join(VENDOR_DIR, 'vendor.lock.json');
const LOCK_BASENAME = 'vendor.lock.json';
const REQUIRED_NOTICE_PAIRS = [
  {
    bundle: 'isomorphic-git/isomorphic-git.umd.min.js',
    notice: 'isomorphic-git/index.umd.min.js.LICENSE.txt',
  },
] as const;

const sha256 = (buf: Buffer | Uint8Array): string =>
  createHash('sha256').update(buf).digest('hex');

/** Every file under extension/vendor/ (repo-relative to vendor/, sorted), excluding the lock itself. */
const listVendorFiles = (): string[] =>
  (readdirSync(VENDOR_DIR, { recursive: true, withFileTypes: true }) as import('node:fs').Dirent[])
    .filter((d) => d.isFile())
    .map((d) => {
      const parent = String((d as { parentPath?: string; path?: string }).parentPath ?? (d as { path?: string }).path);
      const rel = join(parent, d.name).slice(VENDOR_DIR.length + 1);
      return rel.split('\\').join('/');
    })
    .filter((rel) => rel !== LOCK_BASENAME && !rel.endsWith('/.DS_Store') && rel !== '.DS_Store')
    .sort();

export const computeVendorHashes = (): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const rel of listVendorFiles()) {
    out[rel] = sha256(readFileSync(join(VENDOR_DIR, rel)));
  }
  return out;
};

const writeLock = (): void => {
  const files = computeVendorHashes();
  const lock = {
    '//': 'Generated by `bun packaging/check-vendor.ts --write` — do not hand-edit. '
      + 'Pins every file under extension/vendor/ by SHA-256; verified by `bun run check:vendor` in CI and preflight. '
      + 'Regenerate in the SAME commit as any vendored change, alongside the dir\'s SOURCE.txt update.',
    files,
  };
  writeFileSync(VENDOR_LOCK_PATH, JSON.stringify(lock, null, 2) + '\n');
  console.log(`wrote ${LOCK_BASENAME}: ${Object.keys(files).length} files pinned`);
};

const checkLock = (): void => {
  if (!existsSync(VENDOR_LOCK_PATH)) {
    console.error(`check-vendor FAILED: ${VENDOR_LOCK_PATH} missing — run \`bun packaging/check-vendor.ts --write\` and commit it.`);
    process.exit(1);
  }
  const lock = JSON.parse(readFileSync(VENDOR_LOCK_PATH, 'utf8')) as { files: Record<string, string> };
  const actual = computeVendorHashes();
  const problems: string[] = [];
  // why: minifiers commonly leave a license-file pointer while packaging
  // drops the referenced sidecar. Hashing alone would faithfully pin that
  // non-compliant state, so the relationship itself is a release invariant.
  for (const pair of REQUIRED_NOTICE_PAIRS) {
    if (!Object.hasOwn(actual, pair.notice)) problems.push(`missing required notice: ${pair.notice}`);
    if (Object.hasOwn(actual, pair.bundle)) {
      const bundle = readFileSync(join(VENDOR_DIR, pair.bundle), 'utf8');
      const basename = pair.notice.slice(pair.notice.lastIndexOf('/') + 1);
      if (!bundle.includes(basename)) problems.push(`bundle does not reference required notice: ${pair.bundle}`);
    }
  }
  for (const [rel, hash] of Object.entries(lock.files)) {
    if (!(rel in actual)) problems.push(`missing:  ${rel} (pinned in lock, gone from disk)`);
    else if (actual[rel] !== hash) problems.push(`changed:  ${rel}`);
  }
  for (const rel of Object.keys(actual)) {
    if (!Object.hasOwn(lock.files, rel)) problems.push(`unpinned: ${rel} (on disk, absent from lock)`);
  }
  if (problems.length > 0) {
    console.error(
      'check-vendor FAILED — extension/vendor/ diverges from vendor.lock.json:\n'
      + problems.map((p) => `  ${p}`).join('\n')
      + '\n\nIf this is a deliberate re-vendoring: update the dir\'s SOURCE.txt, run'
      + '\n`bun packaging/check-vendor.ts --write`, and commit both in the same change.'
      + '\nIf you did NOT change vendored code, treat this as tampering and investigate.',
    );
    process.exit(1);
  }
  console.log(`check-vendor OK: ${Object.keys(actual).length} vendored files match the lock`);
};

if (import.meta.main) {
  if (process.argv.includes('--write')) writeLock();
  else checkLock();
}
