// Generate badges/tscheck.json — a shields.io ENDPOINT badge describing the
// extension's // @ts-check coverage. The README badge reads it via
// img.shields.io/endpoint?url=<raw github url>, so it auto-updates whenever
// coverage changes (the committed JSON is regenerated by `bun run gen:dev` and
// the generated-file drift gate fails CI if it goes stale).
//
// Run: bun run gen:badge   (folded into `bun run gen:dev`)

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { REPO_ROOT } from './lib.ts';
import { computeCoverage } from './tscheck-coverage.ts';
import { laneLogo } from './test-badges.ts';

const { count, total, pct } = computeCoverage();

// Whole percentages render as "100%", fractional as "99.8%".
const pctLabel = Number.isInteger(pct) ? `${pct}%` : `${pct.toFixed(1)}%`;
const color = pct >= 100 ? 'brightgreen' : pct >= 90 ? 'green' : pct >= 75 ? 'yellow' : 'orange';

const badge = {
  schemaVersion: 1,
  label: 'types',
  message: `${pctLabel} // @ts-check`,
  color,
  ...laneLogo('typescript'),
};

const outDir = join(REPO_ROOT, 'badges');
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, 'tscheck.json');
writeFileSync(outPath, `${JSON.stringify(badge, null, 2)}\n`);

console.log(`wrote badges/tscheck.json — ${badge.message} (${count}/${total}, ${color})`);
